[package]
name = "nest_sol"
version = "0.1.0"
description = "Nest Token Solana Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
borsh = "0.10.3"
solana-program = "1.16.24"
spl-token = { version="4.0.0", features = [ "no-entrypoint" ] }
